# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"
  - "pypy"

install:
  - pip install .
  - rm -rf build/

script: ./script/test -vv

# setting sudo to 'false' allows running on travis-ci new infra (docker)
sudo: false
